### PR TITLE
Fix dart:convert "UTF8" -> "utf8".

### PR DESCRIPTION
**Pull request by munificent**
While I was at it, I:

- Removed some unused imports.
- Fixed a deprecated API call.
- Removed the no-longer needed analysis options file.

### CODE REVIEW

**Comment by munificent** [comment]
This is failing Travis on stable, but that's to be expected. I could remove stable from the Travis config, but I don't want to have to worry about re-adding that later after Dart 2 ships to stable. Is it OK if we just don't worry about that for now?

**Comment by kevmoo** [comment]
@munificent – just delete the travis config for stable...

**Review by kevmoo — COMMENTED** [review]
Update changelog?

**Comment by munificent** [comment]
>  just delete the travis config for stable...

Done.

> Update changelog?

I, uh, already did in the original patch?

**Comment by kevmoo** [comment]
> I, uh, already did in the original patch?

I are moron

**Review by kevmoo — APPROVED** [review]

**Pull request merged**
